#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <stdio.h>
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <memory>
#include "Surface.cpp"


class MasterSurface{
private:
	std::vector<std::shared_ptr<Surface>> trike;
	std::shared_ptr<Surface> button_centrodeconstruccion;
	std::shared_ptr<Surface> button_cosechadora;
	std::shared_ptr<Surface> button_cuartelatreides;
	std::shared_ptr<Surface> button_cuartelharkonnen;
	std::shared_ptr<Surface> button_cuartelordos;
	std::shared_ptr<Surface> button_desviador;
	std::shared_ptr<Surface> button_devastador;
	std::shared_ptr<Surface> button_fabricaligera;
	std::shared_ptr<Surface> button_fabricapesada;
	std::shared_ptr<Surface> button_fremen;
	std::shared_ptr<Surface> button_infanterialigera;
	std::shared_ptr<Surface> button_infanteriapesada;
	std::shared_ptr<Surface> button_palacio;
	std::shared_ptr<Surface> button_raider;
	std::shared_ptr<Surface> button_refineria;
	std::shared_ptr<Surface> button_sardaukar;
	std::shared_ptr<Surface> button_silo;
	std::shared_ptr<Surface> button_sonictank;
	std::shared_ptr<Surface> button_tanque;
	std::shared_ptr<Surface> button_trampadeaire;
	std::shared_ptr<Surface> button_trike;
	std::shared_ptr<Surface> centrodeconstruccion;
	std::shared_ptr<Surface> cima;
	std::shared_ptr<Surface> cuartelatreides;
public:
	MasterSurface();
	void init_trike();
	std::vector<std::shared_ptr<Surface>> get_trike_surface();
	void init_button_centrodeconstruccion();
	std::shared_ptr<Surface> get_button_centrodeconstruccion_surface();
	void init_button_cosechadora();
	std::shared_ptr<Surface> get_button_cosechadora_surface();
	void init_button_cuartelatreides();
	std::shared_ptr<Surface> get_button_cuartelatreides_surface();
	void init_button_cuartelharkonnen();
	std::shared_ptr<Surface> get_button_cuartelharkonnen_surface();
	void init_button_cuartelordos();
	std::shared_ptr<Surface> get_button_cuartelordos_surface();
	void init_button_desviador();
	std::shared_ptr<Surface> get_button_desviador_surface();
	void init_button_devastador();
	std::shared_ptr<Surface> get_button_devastador_surface();
	void init_button_fabricaligera();
	std::shared_ptr<Surface> get_button_fabricaligera_surface();
	void init_button_fabricapesada();
	std::shared_ptr<Surface> get_button_fabricapesada_surface();
	void init_button_fremen();
	std::shared_ptr<Surface> get_button_fremen_surface();
	void init_button_infanterialigera();
	std::shared_ptr<Surface> get_button_infanterialigera_surface();
	void init_button_infanteriapesada();
	std::shared_ptr<Surface> get_button_infanteriapesada_surface();
	void init_button_palacio();
	std::shared_ptr<Surface> get_button_palacio_surface();
	void init_button_raider();
	std::shared_ptr<Surface> get_button_raider_surface();
	void init_button_refineria();
	std::shared_ptr<Surface> get_button_refineria_surface();
	void init_button_sardaukar();
	std::shared_ptr<Surface> get_button_sardaukar_surface();
	void init_button_silo();
	std::shared_ptr<Surface> get_button_silo_surface();
	void init_button_sonictank();
	std::shared_ptr<Surface> get_button_sonictank_surface();
	void init_button_tanque();
	std::shared_ptr<Surface> get_button_tanque_surface();
	void init_button_trampadeaire();
	std::shared_ptr<Surface> get_button_trampadeaire_surface();
	void init_button_trike();
	std::shared_ptr<Surface> get_button_trike_surface();
	void init_centrodeconstruccion();
	std::shared_ptr<Surface> get_centrodeconstruccion_surface();
	void init_cima();
	std::shared_ptr<Surface> get_cima_surface();
	void init_cuartelatreides();
	std::shared_ptr<Surface> get_cuartelatreides_surface();
	~MasterSurface();
};