#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <stdio.h>
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <memory>
#include "Surface.cpp"


class MasterSurface{
private:
	std::vector<std::shared_ptr<Surface>> explosionfuerte;
	std::vector<std::shared_ptr<Surface>> explosionpersonaje;
	std::vector<std::shared_ptr<Surface>> explosiontanque;
	std::vector<std::shared_ptr<Surface>> trike;
	std::vector<std::shared_ptr<Surface>> cosechadora;
	std::vector<std::shared_ptr<Surface>> raider;
	std::vector<std::shared_ptr<Surface>> sonictank;
	std::vector<std::shared_ptr<Surface>> tanque;
	std::vector<std::shared_ptr<Surface>> desviador;
	std::vector<std::shared_ptr<Surface>> devastador;
	std::vector<std::shared_ptr<Surface>> fremen;
	std::vector<std::shared_ptr<Surface>> fremen_attack;
	std::vector<std::shared_ptr<Surface>> sardaukar;
	std::vector<std::shared_ptr<Surface>> sardaukar_attack;
	std::vector<std::shared_ptr<Surface>> gusano;
	std::vector<std::shared_ptr<Surface>> infanterialigera;
	std::vector<std::shared_ptr<Surface>> infanteriapesada;
	std::vector<std::shared_ptr<Surface>> infanterialigera_attack;
	std::vector<std::shared_ptr<Surface>> infanteriapesada_attack;
	std::shared_ptr<Surface> button_money;
	std::shared_ptr<Surface> button_centrodeconstruccion;
	std::shared_ptr<Surface> button_cosechadora;
	std::shared_ptr<Surface> button_cuartelatreides;
	std::shared_ptr<Surface> button_cuartelharkonnen;
	std::shared_ptr<Surface> button_cuartelordos;
	std::shared_ptr<Surface> button_desviador;
	std::shared_ptr<Surface> button_devastador;
	std::shared_ptr<Surface> button_fabricaligera;
	std::shared_ptr<Surface> button_fabricapesada;
	std::shared_ptr<Surface> button_fremen;
	std::shared_ptr<Surface> button_infanterialigera;
	std::shared_ptr<Surface> button_infanteriapesada;
	std::shared_ptr<Surface> button_palacio;
	std::shared_ptr<Surface> button_raider;
	std::shared_ptr<Surface> button_refineria;
	std::shared_ptr<Surface> button_sardaukar;
	std::shared_ptr<Surface> button_silo;
	std::shared_ptr<Surface> button_sonictank;
	std::shared_ptr<Surface> button_tanque;
	std::shared_ptr<Surface> button_trampadeaire;
	std::shared_ptr<Surface> button_trike;

	std::shared_ptr<Surface> button_roca;
	std::shared_ptr<Surface> button_cima;
	std::shared_ptr<Surface> button_especiafuerte;
	std::shared_ptr<Surface> button_especiasuave;
	std::shared_ptr<Surface> button_duna;
	std::shared_ptr<Surface> button_precipicio;
	std::shared_ptr<Surface> button_save;
	std::shared_ptr<Surface> button_delete;


	std::shared_ptr<Surface> centrodeconstruccion;
	std::shared_ptr<Surface> cima;
	std::shared_ptr<Surface> cuartelatreides;
	std::shared_ptr<Surface> cuartelharkonnen;
	std::shared_ptr<Surface> cuartelordos;
	std::shared_ptr<Surface> fabricaligera;
	std::shared_ptr<Surface> fabricapesada;
	std::shared_ptr<Surface> palacio;
	std::shared_ptr<Surface> refineria;
	std::shared_ptr<Surface> silo;
	std::shared_ptr<Surface> trampadeaire;
	std::shared_ptr<Surface> duna;
	std::shared_ptr<Surface> especiafuerte;
	std::shared_ptr<Surface> especiasuave;
	std::shared_ptr<Surface> precipicio;
	std::shared_ptr<Surface> roca;
	std::shared_ptr<Surface> pointer;

public:
	MasterSurface();
	void init_trike();
	std::vector<std::shared_ptr<Surface>> get_trike_surface();
	void init_cosechadora();
	std::vector<std::shared_ptr<Surface>> get_cosechadora_surface();
	void init_desviador();
	std::vector<std::shared_ptr<Surface>> get_desviador_surface();
	void init_devastador();
	std::vector<std::shared_ptr<Surface>> get_devastador_surface();
	void init_raider();
	std::vector<std::shared_ptr<Surface>> get_raider_surface();
	void init_sonictank();
	std::vector<std::shared_ptr<Surface>> get_sonictank_surface();
	void init_tanque();
	std::vector<std::shared_ptr<Surface>> get_tanque_surface();
	void init_fremen();
	std::vector<std::shared_ptr<Surface>> get_fremen_surface();
	std::vector<std::shared_ptr<Surface>> get_fremenattack_surface();
	void init_infanterialigera();
	void init_infanteriapesada();
	std::vector<std::shared_ptr<Surface>> get_infanterialigera_surface();
	std::vector<std::shared_ptr<Surface>> get_infanterialigeraattack_surface();
	std::vector<std::shared_ptr<Surface>> get_infanteriapesada_surface();
	std::vector<std::shared_ptr<Surface>> get_infanteriapesadaattack_surface();
	void init_sardaukar();
	std::vector<std::shared_ptr<Surface>> get_sardaukar_surface();
	std::vector<std::shared_ptr<Surface>> get_sardaukarattack_surface();
	void init_gusano();
	std::vector<std::shared_ptr<Surface>> get_gusano_surface();
	void init_button_centrodeconstruccion();
	std::shared_ptr<Surface> get_button_centrodeconstruccion_surface();
	void init_button_cosechadora();
	std::shared_ptr<Surface> get_button_cosechadora_surface();
	void init_button_cuartelatreides();
	std::shared_ptr<Surface> get_button_cuartelatreides_surface();
	void init_button_cuartelharkonnen();
	std::shared_ptr<Surface> get_button_cuartelharkonnen_surface();
	void init_button_cuartelordos();
	std::shared_ptr<Surface> get_button_cuartelordos_surface();
	void init_button_desviador();
	std::shared_ptr<Surface> get_button_desviador_surface();
	void init_button_devastador();
	std::shared_ptr<Surface> get_button_devastador_surface();
	void init_button_fabricaligera();
	std::shared_ptr<Surface> get_button_fabricaligera_surface();
	void init_button_fabricapesada();
	std::shared_ptr<Surface> get_button_fabricapesada_surface();
	void init_button_fremen();
	std::shared_ptr<Surface> get_button_fremen_surface();
	void init_button_infanterialigera();
	std::shared_ptr<Surface> get_button_infanterialigera_surface();
	void init_button_infanteriapesada();
	std::shared_ptr<Surface> get_button_infanteriapesada_surface();
	void init_button_palacio();
	std::shared_ptr<Surface> get_button_palacio_surface();
	void init_button_raider();
	std::shared_ptr<Surface> get_button_raider_surface();
	void init_button_refineria();
	std::shared_ptr<Surface> get_button_refineria_surface();
	void init_button_sardaukar();
	std::shared_ptr<Surface> get_button_sardaukar_surface();
	void init_button_silo();
	std::shared_ptr<Surface> get_button_silo_surface();
	void init_button_sonictank();
	std::shared_ptr<Surface> get_button_sonictank_surface();
	void init_button_tanque();
	std::shared_ptr<Surface> get_button_tanque_surface();
	void init_button_trampadeaire();
	std::shared_ptr<Surface> get_button_trampadeaire_surface();
	void init_button_trike();
	std::shared_ptr<Surface> get_button_trike_surface();
	void init_button_money();
	std::shared_ptr<Surface> get_button_money_surface();
	void init_centrodeconstruccion();
	std::shared_ptr<Surface> get_centrodeconstruccion_surface();
	void init_palacio();
	std::shared_ptr<Surface> get_palacio_surface();
	void init_refineria();
	std::shared_ptr<Surface> get_refineria_surface();
	void init_silo();
	std::shared_ptr<Surface> get_silo_surface();
	void init_trampadeaire();
	std::shared_ptr<Surface> get_trampadeaire_surface();
	void init_pointer();
	std::shared_ptr<Surface> get_pointer_surface();
	void init_cima();
	std::shared_ptr<Surface> get_cima_surface();
	void init_duna();
	std::shared_ptr<Surface> get_duna_surface();
	void init_especiafuerte();
	std::shared_ptr<Surface> get_especiafuerte_surface();
	void init_especiasuave();
	std::shared_ptr<Surface> get_especiasuave_surface();
	void init_precipicio();
	std::shared_ptr<Surface> get_precipicio_surface();
	void init_roca();
	std::shared_ptr<Surface> get_roca_surface();
	void init_cuartelatreides();
	std::shared_ptr<Surface> get_cuartelatreides_surface();
	void init_cuartelharkonnen();
	std::shared_ptr<Surface> get_cuartelharkonnen_surface();
	void init_cuartelordos();
	std::shared_ptr<Surface> get_cuartelordos_surface();
	void init_fabricaligera();
	std::shared_ptr<Surface> get_fabricaligera_surface();
	void init_fabricapesada();
	std::shared_ptr<Surface> get_fabricapesada_surface();
	void init_explosionpersonaje();
	std::vector<std::shared_ptr<Surface>> get_explosionpersonaje_surface();
	void init_explosionfuerte();
	std::vector<std::shared_ptr<Surface>> get_explosionfuerte_surface();
	void init_explosiontanque();
	std::vector<std::shared_ptr<Surface>> get_explosiontanque_surface();

	void init_button_cima();
	std::shared_ptr<Surface> get_button_cima_surface();
	void init_button_duna();
	std::shared_ptr<Surface> get_button_duna_surface();
	void init_button_precipicio();
	std::shared_ptr<Surface> get_button_precipicio_surface();
	void init_button_especiafuerte();
	std::shared_ptr<Surface> get_button_especiafuerte_surface();
	void init_button_especiasuave();
	std::shared_ptr<Surface> get_button_especiasuave_surface();
	void init_button_roca();
	std::shared_ptr<Surface> get_button_roca_surface();
	void init_button_save();
	std::shared_ptr<Surface> get_button_save_surface();
	void init_button_cancel();
	std::shared_ptr<Surface> get_button_cancel_surface();


	~MasterSurface();
};

